name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION_STRING: ${{vars.DB_CONNECTION_STRING}}
      NODEMON_API: ${{vars.NODEMON_API}}
      NODEMON_API_KEY: ${{vars.NODEMON_API_KEY}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.DIGITALOCEAN_HOST}}
        username: ${{secrets.DIGITALOCEAN_USERNAME}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        script: |
          npm -v
          git clone git@github.com:troquilho/test-dashboard-api.git
          cd test-dashboard-api
          npm install
          export DB_CONNECTION_STRING="${DB_CONNECTION_STRING}"
          export NODEMON_API="${NODEMON_API}"
          export NODEMON_API_KEY="${NODEMON_API_KEY}"
          npm run dev